CREATE TABLE "rsi_values" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "candle_id" int,
  "value" float,
  "param" json
);

CREATE TABLE "macd_values" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "candle_id" int,
  "macd_line" float,
  "signal_line" float,
  "histogram" float,
  "param" json
);

CREATE TABLE "market_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset_id" int,
  "timeframe_id" int,
  "open_time" timestamp,
  "open" float,
  "high" float,
  "low" float,
  "close" float,
  "volume" float
);

ALTER TABLE market_data ADD CONSTRAINT unique_candle UNIQUE (asset_id, timeframe_id, open_time);

CREATE TABLE "asset" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "timeframe" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar,
  "minutes" int
);

CREATE INDEX ON "rsi_values" ("candle_id");

CREATE INDEX ON "macd_values" ("candle_id");

CREATE INDEX ON "market_data" ("asset_id", "open_time");