CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "password_hash" varchar,
  "created_at" timestamp,
  "last_login" timestamp
);