CREATE TABLE "strategies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "asset_id" int,
  "stop_loss" float,
  "take_profit" float,
  "risk_per_trade" float,
  "fees" float,
  "slippage" float,
  "created_at" timestamp
);

CREATE TABLE "strategy_indicators" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "strategy_id" int,
  "indicator_id" int,
  "indicator_param" json
);

CREATE TABLE "indicator" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);