CREATE TABLE "backtest" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timeframe_id" int,
  "strategy_id" int,
  "capital" float,
  "period_start" timestamp,
  "period_end" timestamp,
  "performance_pct" float,
  "drawdown_max" float,
  "drawdown_average" float,
  "capital_gain" float,
  "average_capital_gain_per_trade" float,
  "trade_win_rate" float,
  "created_at" timestamp
);

CREATE TABLE "trade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "backtest_id" int,
  "price_enter" float,
  "price_exit" float,
  "pnl_pct" float,
  "pnl_value" float,
  "entry_time" timestamp,
  "exit_time" timestamp,
  "position_type_id" int
);

CREATE TABLE "position_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar
);